'use strict';
// Index — main process. Window lifecycle + the note:// attachment protocol.

const { app, BrowserWindow, protocol, net } = require('electron');
const path = require('path');
const { pathToFileURL } = require('url');
const { registerIpc } = require('./main/ipc');
const store = require('./main/store');
const backup = require('./main/backup');

const DEV = process.argv.includes('--dev');

// The note:// scheme serves files out of data/attachments without
// relaxing webSecurity (plain file:// loads from the renderer are blocked).
protocol.registerSchemesAsPrivileged([
  { scheme: 'note', privileges: { standard: true, secure: true, supportFetchAPI: true, stream: true } },
]);

app.whenReady().then(async () => {
  store.ensureDirs();
  registerIpc();
  // Integrity check + auto-restore, today's snapshot, retention, catch-up
  // sync — all before the window exists, so the renderer never sees a
  // half-recovered data folder. Never blocks startup on failure.
  await backup.runStartupChecks();

  protocol.handle('note', (request) => {
    const url = new URL(request.url);
    // Only note://attachments/<file> is ever served; the path is sandboxed
    // to the attachments dir and names are generated by the app (no user paths).
    // "note" is a standard scheme, so note://attachments/x.png parses with
    // host === 'attachments' and pathname === '/x.png'.
    const fileName = decodeURIComponent(url.pathname.replace(/^\/+/, ''));
    if (url.host !== 'attachments' || !fileName || fileName.includes('/') || fileName.includes('..')) {
      return new Response('Not found', { status: 404 });
    }
    const filePath = path.join(store.ATTACHMENTS_DIR, fileName);
    return net.fetch(pathToFileURL(filePath).toString());
  });

  const win = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 960,
    minHeight: 640,
    title: 'Index',
    backgroundColor: '#171a1d',
    titleBarStyle: 'hiddenInset',
    trafficLightPosition: { x: 14, y: 18 },
    vibrancy: 'under-window',
    show: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // Settings → Fonts enumerates the locally installed families via
  // window.queryLocalFonts(); Chromium gates it behind this permission.
  win.webContents.session.setPermissionRequestHandler((_wc, permission, cb) => {
    cb(permission === 'local-fonts');
  });
  win.webContents.session.setPermissionCheckHandler((_wc, permission) => permission === 'local-fonts');

  win.once('ready-to-show', () => win.show());

  // Surface renderer problems in the terminal — invaluable for debugging.
  // Electron ≥30 passes a details object; older builds pass (e, level, msg, ...).
  win.webContents.on('console-message', (...args) => {
    const [e, legacyLevel, legacyMsg] = args;
    const level = typeof e.level === 'number' ? e.level : legacyLevel;
    const message = e.message ?? legacyMsg;
    if (level >= 2) console.error('[renderer]', message);
  });
  win.webContents.on('render-process-gone', (_e, details) => {
    console.error('[renderer] gone:', details.reason, details.exitCode);
  });
  win.webContents.on('did-fail-load', (_e, code, desc, url) => {
    console.error('[renderer] load failed:', code, desc, url);
  });

  if (DEV) {
    win.webContents.openDevTools({ mode: 'detach' });
    // F5 reloads, like a dev server.
    win.webContents.on('before-input-event', (_e, input) => {
      if (input.type === 'keyDown' && input.key === 'F5') win.reload();
    });
  }

  win.loadFile(path.join(__dirname, 'renderer', 'index.html')).then(() => {
    if (process.env.INDEX_SMOKE) smokeTest(win);
    if (process.env.INDEX_SHOT) screenshot(win, process.env.INDEX_SHOT);
  });
});

// ---- Screenshot (INDEX_SHOT=<path>): capture the window for review ----

async function screenshot(win, spec) {
  // spec = <path>[:view] where view may itself contain colons (page:<id>),
  // and may end in @<selector> to click that element before capturing.
  const colon = spec.indexOf(':');
  const outPath = colon === -1 ? spec : spec.slice(0, colon);
  let view = colon === -1 ? null : spec.slice(colon + 1);
  let clickSel = null;
  if (view && view.includes('@')) {
    const at = view.lastIndexOf('@');
    clickSel = view.slice(at + 1);
    view = view.slice(0, at);
  }
  await new Promise(r => setTimeout(r, 2500)); // let the first view settle
  if (view) {
    if (view.startsWith('page:')) {
      const pageId = view.slice(5);
      await win.webContents.executeJavaScript(`(() => { try { window.__index.openPage(${JSON.stringify(pageId)}); return 'ok'; } catch (e) { return 'THREW: ' + e.stack; } })()`, true)
        .then(r => { if (String(r).startsWith('THREW')) console.log(r); })
        .catch(err => console.log('EVAL ERR:', err && (err.stack || err.message || err)));
    } else {
      await win.webContents.executeJavaScript(`window.__index.goto(${JSON.stringify(view)})`, true)
        .catch(err => console.log('EVAL ERR:', err && (err.stack || err.message || err)));
    }
    if (clickSel) {
      await new Promise(r => setTimeout(r, 500)); // let the view's async render land
      if (clickSel.startsWith('eval:')) {
        // Debug escape hatch: run JS in the page and print the result.
        await win.webContents.executeJavaScript(clickSel.slice(5), true)
          .then(r => console.log('EVAL RESULT:', JSON.stringify(r)))
          .catch(err => console.log('EVAL ERR:', err && (err.stack || err.message || err)));
      } else {
        await win.webContents.executeJavaScript(
          `(() => { const el = document.querySelector(${JSON.stringify(clickSel)}); if (!el) return 'NO MATCH: ' + ${JSON.stringify(clickSel)}; el.click(); return 'ok'; })()`, true)
          .then(r => { if (r !== 'ok') console.log('CLICK:', r); })
          .catch(err => console.log('EVAL ERR:', err && (err.stack || err.message || err)));
      }
    }
    await new Promise(r => setTimeout(r, 800));
  }
  // An occluded/backgrounded window gets its rendering throttled, and
  // capturePage then returns the last frame before throttling kicked in —
  // a screenshot of a view that no longer exists. Force the window front
  // and nudge a resize so the compositor paints the current DOM first.
  if (process.platform === 'darwin') app.focus({ steal: true });
  win.show();
  const [w, h] = win.getSize();
  win.setSize(w + 1, h);
  win.setSize(w, h);
  await new Promise(r => setTimeout(r, 400));
  const image = await win.webContents.capturePage();
  require('fs').writeFileSync(outPath, image.toPNG());
  console.log('SHOT saved:', outPath);
  app.quit();
}

// ---- Smoke test (INDEX_SMOKE=1): drives the real UI end-to-end ----

async function smokeTest(win) {
  const ev = (code) => win.webContents.executeJavaScript(code, true);
  const results = [];
  const step = async (name, code) => {
    try {
      const r = await ev(code);
      results.push([name, r]);
      console.log(`SMOKE ${name}: ${JSON.stringify(r)}`);
    } catch (err) {
      results.push([name, `ERROR: ${String(err)}`]);
      console.log(`SMOKE ${name}: ERROR ${String(err)}`);
    }
  };
  const sleep = (ms) => new Promise(r => setTimeout(r, ms));

  await sleep(1500); // let the app boot + first render

  await step('dashboard-rendered', `!!document.querySelector('.dashboard')`);
  await step('nav-buttons', `document.querySelectorAll('.nav-btn').length`);
  await step('theme', `document.documentElement.dataset.theme`);
  await step('welcome-page-in-tree', `window.api.listPages().then(ps => ps.length >= 1)`);

  // Create a smoke project (= notebook) with a sub-objective holding an
  // overdue + a today task, plus a floating task, through the real API layer.
  const today = new Date().toISOString().slice(0, 10);
  await step('create-project', `window.api.createNotebook('Smoke Test').then(r => { window.__smokeNb = r.notebook.id; return !!r.notebook; })`);
  await step('create-sub-objective', `window.api.createSection(window.__smokeNb, 'Smoke sub-objective').then(r => { window.__smokeSec = r.section.id; return !!r.section; })`);
  await step('add-tasks', `window.api.saveTask(window.__smokeNb, ${JSON.stringify({
    id: 't_smoke_over', title: 'Overdue smoke task', status: 'todo', priority: 'high', dueDate: '2020-01-01',
  })}, window.__smokeSec).then(r => window.api.saveTask(window.__smokeNb, ${JSON.stringify({
    id: 't_smoke_today', title: 'Today smoke task', status: 'todo', priority: 'normal', dueDate: today,
  })}, window.__smokeSec).then(() => window.api.saveTask(window.__smokeNb, ${JSON.stringify({
    id: 't_smoke_float', title: 'Floating smoke task', status: 'todo', priority: 'normal', dueDate: null,
  })}, null).then(() => true)))`);
  await step('refresh-tree', `window.__index.refreshTree().then(b => b.notebooks.notebooks.length >= 1)`);

  await step('goto-dashboard', `window.__index.goto('dashboard').then(() =>
    !!(document.querySelector('.dash-projects') || document.querySelector('.ring-plate, .ring-empty')))`);
  await step('overdue-chip', `!!document.querySelector('.chip-overdue')`);
  await step('upcoming-afloat', `!!document.querySelector('.upcoming-item.is-afloat')`);
  await step('briefing-panel', `!!document.querySelector('.brief')`);

  // The user's live pane-fold state must not fail the run. notes defaults
  // folded — false unfolds it explicitly.
  await step('unfold-panes', `window.api.setSetting('paneFold', { notes: false }).then(() => window.__index.refreshTree()).then(() => true)`);
  await step('goto-projects', `window.__index.goto('projects').then(() => !!document.querySelector('.project-row'))`);
  await step('select-project', `(window.__index.goto('projects', {currentProjectId: window.__smokeNb}), true)`);
  await sleep(300);
  await step('big-picture-banner', `!!document.querySelector('.ql-question')`);
  await step('dress-default', `!!document.querySelector('.fp-tasks.dress-quiet-console, .fp-tasks[class*="dress-"]')`);
  await step('project-detail', `document.querySelector('.ql-project-name')?.textContent`);
  await step('sub-objective', `[...document.querySelectorAll('.fp-sub-name')].map(e => e.textContent)`);
  await step('afloat-block', `!!document.querySelector('.fp-afloat')`);
  // The unfiled box starts tucked away; the header opens and closes it.
  await step('afloat-toggle', `(async () => {
    await window.api.setSetting('afloatOpen', true);
    await window.__index.refreshTree();
    window.__index.goto('projects');
    await new Promise(r => setTimeout(r, 250));
    const open = !!(document.querySelector('.fp-afloat .ql-add-title'));
    await window.api.setSetting('afloatOpen', false);
    await window.__index.refreshTree();
    window.__index.goto('projects');
    await new Promise(r => setTimeout(r, 250));
    const closed = !!(document.querySelector('.fp-afloat') && !document.querySelector('.fp-afloat .ql-add-title'));
    return { open, closed };
  })()`);
  await step('task-rows', `document.querySelectorAll('.ql-task').length`);
  await step('day-rows', `document.querySelectorAll('.ql-day').length`);
  await step('task-pills', `[...document.querySelectorAll('.ql-task-due-pill, .ql-task-carried')].map(e => e.textContent).slice(0,2)`);
  await step('big-picture-set', `window.api.setBigPicture(window.__smokeNb, 'The smoke test writes a big picture').then(() => window.__index.refreshTree()).then(() => window.__index.goto('projects')).then(() => true)`);
  await sleep(400);
  await step('big-picture-shows', `(document.querySelector('.ql-question-text')?.textContent || '').includes('smoke test writes a big picture')`);
  // The outcome: the answer hangs off its question on the vertical tie.
  await step('big-picture-resolved', `window.api.resolveBigPicture(window.__smokeNb, 'The smoke test says gene B').then(() => window.__index.refreshTree()).then(() => window.__index.goto('projects')).then(() => true)`);
  await sleep(400);
  await step('big-picture-resolves', `(() => {
    const t = document.querySelector('.ql-res-text')?.textContent || '';
    const tie = !!document.querySelector('.ql-res-tie');
    return tie && t.includes('smoke test says gene B');
  })()`);
  await step('notes-index', `!!document.querySelector('.fp-notes-index')`);

  await step('open-welcome-page', `window.api.listPages().then(ps => { window.__index.openPage(ps[0].id); return true; })`);
  await sleep(400);
  await step('page-editor', `document.querySelector('.page-title-input')?.value`);
  await step('editor-blocks', `document.querySelectorAll('#editor-host .block').length`);

  // Reading view: compile the smoke project through the real UI.
  await step('goto-log', `(window.__index.goto('log'), true)`);
  await sleep(400);
  await step('open-reading', `(() => { const b = [...document.querySelectorAll('.dash-nav button[data-open]')].find(x => x.dataset.open === 'reading'); b.click(); return !!b; })()`);
  await sleep(600);
  await step('reading-view', `!!document.querySelector('.rv-wrap')`);
  await step('reading-scope-options', `document.querySelectorAll('#rv-scope option').length`);

  await step('goto-settings', `window.__index.goto('settings').then(() => document.querySelectorAll('.theme-card').length)`);
  await sleep(400); // backup status renders via its own IPC round-trip
  await step('backup-status', `document.querySelectorAll('#backup-status .backup-row').length`);

  await step('goto-threads', `(window.__index.goto('threads'), true)`);
  await sleep(600);
  await step('threads-band-cols', `document.querySelectorAll('.tl-col').length`);
  // Column heights ride data + the CSSOM (the CSP blocks style
  // attributes), so the computed heights are the proof the band's
  // weight ever applied — a loud day stands tall, a quiet one lies flat.
  await step('threads-band-heights', `(() => {
    const hs = [...document.querySelectorAll('.tl-bar')].map(b => b.getBoundingClientRect().height);
    return hs.length > 10 && Math.max(...hs) >= 8 && Math.min(...hs) <= 2;
  })()`);
  await step('threads-day-selected', `!!document.querySelector('.tl-day-head')`);
  await step('threads-scrolled-right', `document.querySelector('.tl-band-wrap').scrollLeft > 0`);

  // The sky layout: the same view as constellations. The smoke project
  // guarantees at least one, so the SVG must render with stars in it — and
  // its big picture must show as a question label, which the top-left
  // toggle hides and brings back.
  await step('sky-layout', `(async () => {
    let out = false;
    try {
      // A family for the sky: a kin notebook joins the smoke project in
      // one group. The sky must read a family as one thing — same paint,
      // one neighbourhood — so the probes below check both members wear
      // the group's color and sit nearer each other than any stranger.
      const boot0 = await window.api.bootstrap();
      const uniId = (boot0.settings && boot0.settings.currentUniverse) ||
        (boot0.notebooks.universes[0] && boot0.notebooks.universes[0].id);
      const kin = await window.api.createNotebook('Smoke Kin', uniId);
      window.__smokeKin = kin.notebook.id;
      const grp = await window.api.saveGroup(
        { id: 'grp_smoke_sky', name: 'Smoke Sky Family', color: '#b48ead', parentId: null, universeId: uniId });
      window.__smokeGrp = grp.group.id;
      await window.api.saveHunt(window.__smokeNb, { groupId: grp.group.id });
      await window.api.saveHunt(window.__smokeKin, { groupId: grp.group.id });
      // Grouping moves big-picture ownership to the group, so the
      // question and its outcome are re-stamped from a member — they
      // must land on the family for the probes below to find them.
      await window.api.setBigPicture(window.__smokeNb, 'The smoke test writes a big picture');
      await window.api.resolveBigPicture(window.__smokeNb, 'The smoke test says gene B');
      await window.api.setSetting('threadsLayout', 'sky');
      await window.__index.refreshTree();
      await window.__index.goto('threads');
      await new Promise(r => setTimeout(r, 700));
      const svg = document.querySelector('#sky-svg');
      // The background stars are gone — the constellation's own stars are
      // what must render, at least one per project.
      const okStars = !!(svg && svg.querySelectorAll('.sky-star').length > 0);
      // Hub names carry their size through the CSSOM — the CSP blocks
      // style attributes, so the computed size is the only honest proof
      // the sky's type ever applied.
      const nameEl = svg?.querySelector('.sky-name');
      const wantPx = nameEl ? parseFloat(
        (nameEl.style.fontSize.match(/calc\\(([\\d.]+)px/) || [])[1] || '0') *
        (parseFloat(document.documentElement.style.getPropertyValue('--ui-scale')) || 1) : 0;
      const sizeOk = !!nameEl &&
        Math.abs(parseFloat(getComputedStyle(nameEl).fontSize) - wantPx) < 0.5;
      // The smoke label may not be the first plate — other projects keep
      // their own questions, so the probe reads every label.
      const labelThere = () =>
        [...document.querySelectorAll('#sky-svg .sky-q-label')].map(t => t.textContent).join('')
          .replace(/\\s+/g, '').includes('smoketestwritesabigpicture');
      const qOn = labelThere();
      // The outcome plate answers its question on a dashed diagonal —
      // the smoke project resolves its big picture before the sky.
      const okOutcome = !!(svg && svg.querySelector('.sky-o-box') && svg.querySelector('.sky-q-diag'));
      // The family probes: same paint (the group's, over the steel
      // fallback — both members are born colorless), and one
      // neighbourhood: the two hubs sit closer to each other than to
      // any stranger's hub, inside a loose cluster radius.
      const names = [...svg.querySelectorAll('.sky-name')];
      const pos = (t) => [parseFloat(t.getAttribute('x')), parseFloat(t.getAttribute('y'))];
      const smokeName = names.find(t => t.textContent === 'Smoke Test');
      const kinName = names.find(t => t.textContent === 'Smoke Kin');
      const colorOk = !!(smokeName && kinName &&
        smokeName.getAttribute('fill') === '#b48ead' &&
        kinName.getAttribute('fill') === '#b48ead');
      let nearOk = false;
      if (smokeName && kinName) {
        const A = pos(smokeName), B = pos(kinName);
        const fam = Math.hypot(A[0] - B[0], A[1] - B[1]);
        const others = names.filter(t => t !== smokeName && t !== kinName).map(pos);
        const nearest = Math.min(
          ...others.map(P => Math.hypot(P[0] - A[0], P[1] - A[1])),
          ...others.map(P => Math.hypot(P[0] - B[0], P[1] - B[1])));
        nearOk = fam < 170 && (others.length === 0 || fam < nearest);
      }
      document.querySelector('#sky-q-toggle button[data-q="off"]').click();
      await new Promise(r => setTimeout(r, 400));
      // The toggle hides the plates in place — the label element stays in the
      // DOM, so "hidden" reads as the svg carrying .q-off and the label
      // displayed none. The outcome is one unit with its question: it hides
      // and returns on the same toggle.
      const svgAfter = document.querySelector('#sky-svg');
      const qHidden = !!svgAfter?.classList.contains('q-off') &&
        getComputedStyle(svgAfter.querySelector('.sky-q-label')).display === 'none' &&
        (!svgAfter.querySelector('.sky-o-box') ||
          getComputedStyle(svgAfter.querySelector('.sky-o-box')).display === 'none');
      document.querySelector('#sky-q-toggle button[data-q="on"]').click();
      await new Promise(r => setTimeout(r, 700));
      const qBack = labelThere();
      out = okStars && sizeOk && okOutcome && colorOk && nearOk && qOn && qHidden && qBack;
    } finally {
      // However the probes went, the family disbands and the sky never
      // stays up after this step — a stuck setting fails every later
      // run's day-view probes.
      if (window.__smokeKin) await window.api.deleteNotebook(window.__smokeKin).catch(() => {});
      if (window.__smokeGrp) await window.api.deleteGroup(window.__smokeGrp).catch(() => {});
      await window.api.setSetting('skyQuestions', true);
      await window.api.setSetting('threadsLayout', 'days');
      await window.__index.refreshTree();
      await window.__index.goto('threads');
    }
    return out;
  })()`);

  await step('search', `window.api.search('welcome').then(rs => rs.length >= 1)`);

  // Clean up: the smoke project dies with its notebook (sections, tasks,
  // and pages all hang off it). Activity lines are trimmed by hand after
  // the run, as ever.
  await step('cleanup-notebook', `window.api.deleteNotebook(window.__smokeNb).then(() => true)`);

  const failures = results.filter(([n, r]) => r === false || r === null || r === undefined || String(r).startsWith('ERROR'));
  console.log(failures.length ? `SMOKE FAILED: ${failures.map(f => f[0]).join(', ')}` : 'SMOKE PASSED');
  app.quit();
}

// Single-window app: re-open is a no-op, close quits.
app.on('window-all-closed', () => app.quit());
app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) app.relaunch(); // unreachable in practice
});